### ISSUE TITLE
oxAuth favicon upload not working...

### ISSUE THREAD

**Issue by mzico** [GluuFederation/docker-oxauth#50]
![Peek 2022-03-23 13-17](https://user-images.githubusercontent.com/7156097/159781331-e9b92461-7949-4de0-ae9b-f0da7d5ea72b.gif)

Ref: https://github.com/GluuFederation/flex/issues/172

**Comment by iromli** [comment]
@mzico uploading favicon and logo via oxTrust UI wont work due to several reasons:

- uploads expecting `/opt/gluu/jetty/oxauth/custom/static/favicon` and `/opt/gluu/jetty/oxauth/custom/static/logo` directories exist in oxtrust container's filesystem (but there are no such directories in oxtrust container; they lived in oxauth container instead)
- even if `favicon` and `logo` directories for oxauth can be created in oxtrust container, oxauth unable to load favicon and logo as they are lived under oxtrust container

To address this issue, users need to mount favicon and logo files into oxauth and oxtrust container (configmaps can be utilized to mount files into `/opt/gluu/jetty/oxauth/custom/static/favicon` and `/opt/gluu/jetty/oxauth/custom/static/logo`).

**Comment by iromli** [comment]
Apparently, mounting files are not sufficient. The persistence entry need to be updated. See following example in LDAP persistence:

```
dn: o=gluu
oxAuthFaviconPath: /opt/gluu/jetty/oxauth/custom/static/favicon/custom-favicon.png
oxAuthLogoPath: /opt/gluu/jetty/oxauth/custom/static/logo/custom-logo.png
oxTrustFaviconPath: /opt/gluu/jetty/identity/custom/static/favicon/custom-favicon.png
oxTrustLogoPath: /opt/gluu/jetty/identity/custom/static/logo/custom-logo.png
```

I'm proposing adding new env vars to detect custom logo and favicon and update persistence entry.

@moabu what do you think?

**Comment by moabu** [comment]
Yes we can do this and perhaps add something in the deployment in helm to help with easing the env control. Meaning in the docs we would point the users to create their custom cms with the mounts above and default the path to the above without them managing the paths. I'll add that once this is closed in helm and the docs

**Comment by iromli** [comment]
Please refer to https://github.com/GluuFederation/docker-oxauth#uploading-custom-favicon-and-logo for implementation.
